-- =============================================================================
-- V1__create_prompt_logs.sql
--
-- Creates the central audit table for SentinelAI.
--
-- Every prompt that passes through the proxy is recorded here, along with
-- the full AI model response, the risk score returned by the injection
-- detection API, and assorted metadata. This is the source of truth for
-- retroactive audits.
--
-- Design notes:
--   - risk_score is NULLABLE: a null value means the detection API timed out
--     or returned an error. That is a valid audit state, not a data defect.
--   - metadata is JSONB so operators can attach arbitrary key/value pairs
--     (user ID, session ID, department, etc.) without schema migrations.
--   - license_key is stored denormalised here for fast retention queries;
--     the license lookup happens at request time, not at cleanup time.
-- =============================================================================

-- The prompt_logs table stores one row per proxied request.
-- It is the primary data store for the SentinelAI audit trail.
CREATE TABLE prompt_logs (

    -- Surrogate primary key — UUID generated by the application layer so that
    -- it can be included in the API response before the DB write completes.
    id              UUID            NOT NULL,

    -- Wall-clock time when the proxy request was received (not when it was
    -- persisted — the async write happens slightly later).
    -- Stored WITH TIME ZONE so multi-region deployments compare correctly.
    request_time    TIMESTAMPTZ     NOT NULL,

    -- The AI model identifier as reported by the provider
    -- (e.g. "gpt-4o", "claude-3-5-sonnet-20241022", "gemini-1.5-pro").
    model           VARCHAR(128)    NOT NULL,

    -- The raw prompt text sent by the caller. Stored in full because auditors
    -- need the exact content for retroactive injection analysis.
    prompt          TEXT            NOT NULL,

    -- The raw response text returned by the AI model. Stored alongside the
    -- prompt so auditors can evaluate completeness of any injection attempt.
    response        TEXT,

    -- Risk score returned by the injection detection API (0.0 = safe, 1.0 =
    -- high risk). NULL when the detection call timed out or failed — not
    -- storing a 0.0 default avoids false negatives in audit queries.
    risk_score      NUMERIC(5, 4),

    -- Arbitrary JSON metadata supplied by the caller (user_id, session_id,
    -- department, etc.). JSONB is used (not JSON) for efficient GIN indexing
    -- if operators need to filter by metadata fields in future.
    metadata        JSONB,

    -- License key supplied via X-Sentinel-License header on the request.
    -- Denormalised here so the nightly retention job can filter by tier
    -- without joining to a license table on every cleanup run.
    license_key     VARCHAR(256),

    -- Row creation timestamp — set once by the application, never updated.
    -- Distinct from request_time because async persistence may introduce
    -- a small lag; both timestamps are useful for diagnosing pipeline health.
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),

    CONSTRAINT prompt_logs_pkey PRIMARY KEY (id)
);

-- Comment the table itself so pg_stat_user_tables and psql \d+ show context.
COMMENT ON TABLE  prompt_logs IS 'Audit trail for all proxied AI requests — one row per request.';
COMMENT ON COLUMN prompt_logs.id           IS 'UUID PK generated by the application before the DB write.';
COMMENT ON COLUMN prompt_logs.request_time IS 'Wall-clock time the proxy received the request (WITH TIME ZONE).';
COMMENT ON COLUMN prompt_logs.model        IS 'AI model identifier as reported by the provider.';
COMMENT ON COLUMN prompt_logs.prompt       IS 'Full raw prompt text sent by the caller.';
COMMENT ON COLUMN prompt_logs.response     IS 'Full raw response text returned by the AI model.';
COMMENT ON COLUMN prompt_logs.risk_score   IS 'Injection risk 0.0–1.0; NULL means detection call failed.';
COMMENT ON COLUMN prompt_logs.metadata     IS 'Arbitrary caller-supplied JSON (user_id, session, etc.).';
COMMENT ON COLUMN prompt_logs.license_key  IS 'License key from X-Sentinel-License header; drives retention tier.';
COMMENT ON COLUMN prompt_logs.created_at   IS 'Row insertion timestamp (may lag request_time due to async write).';
