package com.sentinelai.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.Map;
import java.util.UUID;

/**
 * JPA entity mapping to the {@code prompt_logs} table.
 *
 * <p>One row is created per proxied AI request and represents the complete
 * audit record for that request: who sent it, which model answered, what
 * was said, what the AI replied, and what the injection detection API
 * scored the prompt.</p>
 *
 * <p>This entity is written exactly once and never updated. Treat rows as
 * immutable audit records — no update operations should exist in the
 * codebase. Deletion is handled only by the scheduled retention job.</p>
 *
 * <h2>Schema ownership</h2>
 * <p>The DDL is owned by Flyway (see {@code V1__create_prompt_logs.sql}).
 * {@code spring.jpa.hibernate.ddl-auto=validate} means Hibernate will throw
 * at startup if this mapping drifts from the actual schema — a deliberate
 * safety net.</p>
 */
@Entity
@Table(name = "prompt_logs")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class PromptLog {

    /**
     * Surrogate primary key — UUID generated by the application before the
     * database write so it can be included in the HTTP response immediately,
     * even though the persistence happens asynchronously after the response
     * has already been sent.
     */
    @Id
    @Column(name = "id", nullable = false, updatable = false)
    private UUID id;

    /**
     * Wall-clock time when the proxy received the request.
     *
     * <p>This is captured at request ingestion time, not at persistence time.
     * The async write may lag by tens of milliseconds; {@code created_at}
     * records when the row was actually inserted. Storing both lets operators
     * measure pipeline latency if needed.</p>
     */
    @Column(name = "request_time", nullable = false, updatable = false)
    private OffsetDateTime requestTime;

    /**
     * AI model identifier as reported by the provider.
     *
     * <p>Examples: {@code "gpt-4o"}, {@code "claude-3-5-sonnet-20241022"},
     * {@code "gemini-1.5-pro"}. Stored verbatim from the proxy request so
     * audit reports can group by model.</p>
     */
    @Column(name = "model", nullable = false, updatable = false, length = 128)
    private String model;

    /**
     * AI provider routing key for this request.
     *
     * <p>Resolved from {@code ProxyRequest.provider} (or the
     * {@code X-Sentinel-Provider} header in future). Stored as the
     * {@link com.sentinelai.model.ModelProvider} enum name
     * (e.g. {@code "OPENAI"}, {@code "ANTHROPIC"}, {@code "GEMINI"},
     * {@code "AZURE_OPENAI"}). Defaults to {@code "OPENAI"} for
     * pre-Phase-5 records where the column was not present.</p>
     *
     * <p>Not nullable — the V3 migration backfills existing rows with
     * {@code 'OPENAI'} and the application always resolves a non-null
     * provider via {@link com.sentinelai.model.ModelProvider#fromString(String)}
     * before building this record.</p>
     */
    @Column(name = "provider", nullable = false, updatable = false, length = 64)
    private String provider;

    /**
     * The full raw prompt text sent by the caller.
     *
     * <p>Stored in full (TEXT, no length cap) because auditors need the exact
     * content to evaluate injection attempts retroactively. Never truncated.</p>
     */
    @Column(name = "prompt", nullable = false, updatable = false, columnDefinition = "TEXT")
    private String prompt;

    /**
     * The full raw response text returned by the AI model.
     *
     * <p>Nullable because the AI call could fail before producing a response.
     * In that case the row is still persisted with a null response so the
     * failed request appears in the audit trail.</p>
     */
    @Column(name = "response", updatable = false, columnDefinition = "TEXT")
    private String response;

    /**
     * Injection risk score returned by the detection API, in the range 0.0–1.0.
     *
     * <p>{@code null} means the detection API call timed out or returned an
     * error. This is a valid audit state — we deliberately do not substitute
     * a default value of 0.0 because that would create false negatives in
     * risk-based audit queries. Operators can query for
     * {@code risk_score IS NULL} to find requests where detection failed.</p>
     */
    @Column(name = "risk_score", updatable = false, precision = 5, scale = 4)
    private BigDecimal riskScore;

    /**
     * Arbitrary metadata supplied by the caller as a JSON object.
     *
     * <p>Common keys include {@code user_id}, {@code session_id},
     * {@code department}, {@code application_name}. The schema is not
     * enforced — operators define their own metadata conventions.
     * Stored as JSONB in PostgreSQL for efficient GIN-indexable querying
     * if operators need to filter by metadata fields.</p>
     */
    @Column(name = "metadata", updatable = false, columnDefinition = "jsonb")
    @JdbcTypeCode(SqlTypes.JSON)
    private Map<String, Object> metadata;

    /**
     * License key supplied by the caller via the {@code X-Sentinel-License}
     * HTTP header.
     *
     * <p>Denormalised here (rather than joined to a license table at query
     * time) so the nightly retention job can compute per-tenant cutoff dates
     * and issue a single {@code DELETE WHERE license_key = ? AND created_at < ?}
     * without any joins, keeping cleanup fast even at scale.</p>
     *
     * <p>Nullable — callers operating on the free tier may omit the header.</p>
     */
    @Column(name = "license_key", updatable = false, length = 256)
    private String licenseKey;

    /**
     * Timestamp when this row was inserted by the async persistence path.
     *
     * <p>Set by the database via {@code DEFAULT NOW()} in the DDL; the
     * application does not set this field. The {@code insertable = false}
     * flag tells Hibernate to omit this column from INSERT statements so
     * the database default fires correctly.</p>
     */
    @Column(name = "created_at", nullable = false, updatable = false, insertable = false)
    private OffsetDateTime createdAt;
}
